# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6caea32517ffc4b93b04901c79e2f03a826640bbd6a5d7b4d3af787315933dbc224670fa79048069468acbf9b0c64f2df71e7427ebfa0b53122167c763c86b73

test:
  secret_key_base: d392deb0d6a3de0cbaf9c41fb69b76bbc1b56317f515fc536aff6dcffe254c5a410eba3a3baa187eb4b6034057a71baf5a2aef6d899c04da39bd61f9523adacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
